name: Sitemap Check

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Run notify sitemap updates
        run: python notify_sitemap_updates.py
        env:
          SITEMAP_URL: ${{ secrets.SITEMAP_URL }}
          SITEMAP_INDEX_URL: ${{ secrets.SITEMAP_INDEX_URL }}

      - uses: matheusalbino/git-commit@v1.1.0
        with:
          user-name: Equal
          user-email: equal@example.com
          message: This a commit from Github Actions
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
